AWSTemplateFormatVersion: "2010-09-09"
Description: file manager stack it lauches ec2 instances, load balancer, security groups, auto scaling
Parameters:
  InstanceType:
    Type: String
Resources:
  InstancesSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow public trafic
      GroupName: instances-sg
      VpcId: !ImportValue mainvpc
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: TCP
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 60000
  LoadBalancerSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow public trafic
      GroupName: load-balancer-sg
      VpcId: !ImportValue mainvpc
      SecurityGroupIngress:
        - IpProtocol: TCP
          CidrIp: 0.0.0.0/0
          FromPort: 8080
          ToPort: 8080
      SecurityGroupEgress:
        - IpProtocol: TCP
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 60000
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref 'InstanceType'
      ImageId: ami-06b09bfacae1453cb
      SubnetId: !ImportValue subnetA
      SecurityGroupIds:
        - !Ref InstancesSg
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !ImportValue mainvpc
      TargetType: instance
      Protocol: HTTP
      Port: 80
      Name: file-manager-tg
      Targets:
        - Id: !Ref Ec2Instance
          Port: 80
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: file-manager-lb
      Type: application
      Subnets:
        - !ImportValue subnetA
        - !ImportValue subnetB
      SecurityGroups:
        - !Ref LoadBalancerSg

