name: Deploy infraestructure
on: push
permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read    # This is required for actions/checkout
jobs:
    deploy-infraestructure:
        runs-on: ubuntu-latest
        steps:
            -   name: clone repository
                uses: actions/checkout@v3
            -   name: configure aws credentials
                uses: aws-actions/configure-aws-credentials@v2
                with:
                    role-to-assume: arn:aws:iam::692060838294:role/gitHubActionRole
                    aws-region: us-east-1