name: Deploy infraestructure
on: push
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  deploy-infraestructure:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::692060838294:role/gitHubActionRole
          aws-region: us-east-1
      - name: Deploy vpc CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: file-manager-vpc
          template: file-manager-vpc.yaml
          parameter-overrides: file:///${{ github.workspace }}/vpc-parameters.json
          no-fail-on-empty-changeset: 1
      - name: Deploy EC2 CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: file-manager-ec2
          template: file-manager-ec2.yaml
          parameter-overrides: file:///${{ github.workspace }}/ec2-parameters.json
          no-fail-on-empty-changeset: 1
